name: pytest
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}-${{ github.event.ref }}
  cancel-in-progress: true
on:
  pull_request:
  push:
    branches: [maint/0.6]
  workflow_dispatch:

jobs:
  pytest:
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu]
        python-version: ["3.10"]
    name: ${{ matrix.os }} - ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install linux dependencies
        if: ${{ matrix.os == 'ubuntu' }}
        run: |
          sudo apt update
          sudo apt install -y libpugixml-dev
      - name: Setup headless display
        uses: pyvista/setup-headless-display-action@main
        with:
          qt: true
      - name: Install dependencies
        run: |
          python -m pip install --progress-bar off --upgrade pip setuptools wheel
          python -m pip install --progress-bar off .[test]
      - name: Display system information
        run: bsl-sys_info --developer
      - name: Run pytest
        run: pytest bsl --cov=bsl --cov-report=xml --cov-config=pyproject.toml
      - name: Upload to codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml
          flags: unittests  # optional
          name: codecov-umbrella  # optional
          fail_ci_if_error: false  # optional (default = false)
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true  # optional (default = false)
